- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create web root directory for {{ item.name }}
  file:
    path: "/var/www/{{ item.name }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"
  loop: "{{ domain_name }}"

- name: Deploy Nginx vhost for {{ item.name }}
  loop: "{{ domain_name }}"
  template:
    src: vhost.conf.j2
    dest: "/etc/nginx/sites-available/{{ item.name }}"
  notify: Reload nginx

- name: Enable site {{ item.name }}
  loop: "{{ domain_name }}"
  file:
    src: "/etc/nginx/sites-available/{{ item.name }}"
    dest: "/etc/nginx/sites-enabled/{{ item.name }}"
    state: link
  notify: Reload nginx

- name: Remove default nginx site
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: Reload nginx

- name: Test nginx config
  command: nginx -t
  register: nginx_test
  changed_when: false
  failed_when: nginx_test.rc != 0