- name: Install certbot
  apt:
    name:
      - certbot
    state: present
    update_cache: yes

- name: "Obtain/renew certificate for {{ item.name }} using ACME HTTP-01 (webroot)"
  loop: "{{ domain_name }}"
  command: >
    certbot certonly
    --webroot
    --webroot-path /var/www/{{ item.name }}
    -d {{ item.name }}
    --non-interactive
    --agree-tos
    -m {{ item.letsencrypt_email }}
  args:
    creates: "/etc/letsencrypt/live/{{ item.name }}/fullchain.pem"